import { ConfigCategory, ConfigKind, ConfigScopeType, NotificationChannel } from '@prisma/client';
import { ConfigDefinition } from './config-definition.types';
import { deepFreeze } from './immutable';

const GLOBAL = [ConfigScopeType.GLOBAL] as const;
const GLOBAL_AND_COUNTRY = [
  ConfigScopeType.GLOBAL,
  ConfigScopeType.COUNTRY,
] as const;

const base = {
  required: false,
  editable: false,
  sensitive: false,
  requiresReason: false,
  requiresConfirmation: false,
  requiresStepUp: false,
  snapshotPolicy: 'NONE' as const,
  validationStrategy: 'SCALAR' as const,
  adminVisible: true,
} as const;

export const CONFIG_DEFINITIONS = deepFreeze(
  Object.freeze([
    {
      ...base,
      key: 'INSTANT_BOOKING_REQUEST_TTL_MINUTES',
      category: ConfigCategory.SESSION,
      domain: 'instant-booking',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 2,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 30,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'How long a practitioner has to respond to a new Instant Booking request.',
      catalog: { slug: 'instant-booking-request-ttl-minutes', displayName: 'Instant request response window', displayNameAr: 'مدة انتظار رد المختص على طلب الجلسة الفورية', description: 'Minutes a practitioner has to accept or reject a new Instant Booking request.', descriptionAr: 'عدد الدقائق المتاحة للمختص لقبول أو رفض طلب جلسة فورية جديد.', configKind: ConfigKind.POLICY },
      seed: { createInitialValue: true, value: 2, priority: 100 },
      uiMetadata: { control: 'integer', impactTextKey: 'impacts.immediate' },
    },
    {
      ...base,
      key: 'INSTANT_BOOKING_PAYMENT_WINDOW_MINUTES',
      category: ConfigCategory.SESSION,
      domain: 'instant-booking',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 5,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 30,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'How long a patient has to pay after an Instant Booking request is accepted.',
      catalog: { slug: 'instant-booking-payment-window-minutes', displayName: 'Instant payment completion window', displayNameAr: 'مهلة إتمام الدفع بعد قبول طلب الجلسة الفورية', description: 'Minutes a patient has to complete payment after acceptance.', descriptionAr: 'عدد الدقائق المتاحة للمريض لإتمام الدفع بعد قبول الطلب.', configKind: ConfigKind.POLICY },
      seed: { createInitialValue: true, value: 5, priority: 100 },
      uiMetadata: { control: 'integer', impactTextKey: 'impacts.immediate' },
    },
    {
      ...base,
      key: 'SESSION_REMINDER_OFFSETS_MINUTES',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'JSON',
      validationStrategy: 'JSON_SCHEMA',
      jsonSchemaId: 'sessions.reminderOffsetsMinutes.v1',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: [60, 15, 0],
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Unique non-negative minutes before session start for pre-start reminders; zero represents the start reminder.',
      catalog: {
        slug: 'session-reminder-offsets-minutes',
        displayName: 'Session Reminder Offsets (Minutes)',
        displayNameAr: 'مواعيد تذكيرات الجلسة بالدقائق',
        description: 'Unique non-negative offsets before start. Include 0 for the start reminder.',
        descriptionAr: 'فواصل زمنية موجبة أو صفرية قبل بداية الجلسة. استخدم 0 لتذكير وقت البداية.',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: true, value: [60, 15, 0], priority: 100 },
      uiMetadata: {
        control: 'integer-list',
        sortable: true,
        uniqueItems: true,
        allowZero: true,
        impactTextKey: 'impacts.session_schedule',
      },
    },
    {
      ...base,
      key: 'SESSION_LATE_REMINDER_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Controls the reminder for participants who have not joined after session start.',
      catalog: {
        slug: 'session-late-reminder-enabled',
        displayName: 'Late Session Reminder Enabled',
        displayNameAr: 'تفعيل تذكير التأخر عن الجلسة',
        description: 'Enable the reminder sent after the session starts when a participant has not joined.',
        descriptionAr: 'تفعيل التذكير بعد بداية الجلسة عند عدم دخول أحد المشاركين.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
      uiMetadata: {
        control: 'toggle',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'SESSION_LATE_REMINDER_MINUTES_AFTER_START',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 5,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 60,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Minutes after session start at which the late-session reminder is due.',
      catalog: {
        slug: 'session-late-reminder-minutes-after-start',
        displayName: 'Late Reminder Minutes After Start',
        displayNameAr: 'دقائق تذكير التأخر بعد بداية الجلسة',
        description: 'Positive delay after the scheduled start for the late-session reminder.',
        descriptionAr: 'المدة الموجبة بعد البداية المحددة لإرسال تذكير التأخر.',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: true, value: 5, priority: 100 },
      uiMetadata: {
        control: 'integer',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'SESSION_JOIN_EARLY_MINUTES',
      category: ConfigCategory.SESSION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 15,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 0,
      maximum: 120,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Minutes before scheduled start when authenticated join becomes available.',
      catalog: {
        slug: 'session-join-early-minutes-v2',
        displayName: 'Session Join Early Minutes',
        displayNameAr: 'دقائق فتح الدخول قبل الجلسة',
        description: 'Configured early join window before the scheduled start.',
        descriptionAr: 'نافذة الدخول القابلة للتهيئة قبل بداية الجلسة.',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: true, value: 15, priority: 100 },
      uiMetadata: {
        control: 'integer',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'SESSION_JOIN_AFTER_END_GRACE_MINUTES',
      category: ConfigCategory.SESSION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 10,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 0,
      maximum: 120,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Minutes after scheduled end during which authenticated reconnect remains available.',
      catalog: {
        slug: 'session-join-after-end-grace-minutes-v2',
        displayName: 'Session Join After-End Grace Minutes',
        displayNameAr: 'دقائق السماح بالدخول بعد نهاية الجلسة',
        description: 'Configured post-end reconnect grace window.',
        descriptionAr: 'نافذة السماح القابلة للتهيئة لإعادة الدخول بعد نهاية الجلسة.',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: true, value: 10, priority: 100 },
      uiMetadata: {
        control: 'integer',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'SESSION_IN_APP_REMINDERS_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Enables in-app delivery for scheduled session reminders.',
      catalog: {
        slug: 'session-in-app-reminders-enabled',
        displayName: 'In-App Session Reminders Enabled',
        displayNameAr: 'تفعيل تذكيرات الجلسات داخل التطبيق',
        description: 'Controls only in-app reminder delivery; it does not change email delivery.',
        descriptionAr: 'يتحكم في إشعارات التطبيق فقط ولا يعطل رسائل البريد الإلكتروني.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
      uiMetadata: {
        control: 'toggle',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'SESSION_EMAIL_REMINDERS_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'FAIL_CLOSED',
      description: 'Enables email delivery for scheduled session reminders.',
      catalog: {
        slug: 'session-email-reminders-enabled',
        displayName: 'Email Session Reminders Enabled',
        displayNameAr: 'تفعيل تذكيرات الجلسات عبر البريد الإلكتروني',
        description: 'Controls only email reminder delivery; it does not change in-app reminders.',
        descriptionAr: 'يتحكم في البريد الإلكتروني فقط ولا يعطل إشعارات التطبيق.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
      uiMetadata: {
        control: 'toggle',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'platform.defaultLocale',
      category: ConfigCategory.LOCALE,
      domain: 'platform',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      validationStrategy: 'STRING_ENUM',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 'en',
      required: true,
      allowedScopes: GLOBAL_AND_COUNTRY,
      allowedValues: ['ar', 'en'],
      editable: true,
      status: 'SEEDED_BUT_UNUSED',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Catalog fallback locale; current runtime authority is documented separately.',
      catalog: {
        slug: 'platform-default-locale',
        displayName: 'Platform Default Locale',
        description: 'Fallback locale when request locale is missing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: true, value: 'ar', priority: 100 },
    },
    {
      ...base,
      key: 'auth.otp.loginTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'auth',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 10,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 60,
      status: 'LEGACY',
      deprecationReason:
        'Runtime authority is AUTH_LOGIN_OTP_TTL_MINUTES in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry duplicated by the authentication environment policy.',
      catalog: {
        slug: 'auth-otp-login-ttl-minutes',
        displayName: 'Practitioner Login OTP TTL Minutes',
        description: 'OTP validity window in minutes for login flow',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'auth.passwordReset.otpTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'auth',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 15,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 60,
      status: 'LEGACY',
      deprecationReason:
        'Runtime authority is AUTH_RESET_PASSWORD_TTL_MINUTES in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry; reset OTP runtime uses environment configuration.',
      catalog: {
        slug: 'auth-password-reset-otp-ttl-minutes',
        displayName: 'Password Reset OTP TTL Minutes',
        description: 'OTP validity window in minutes for password reset',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'security.jwt.accessTokenTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'security',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 30,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 1440,
      status: 'LEGACY',
      deprecationReason: 'Runtime authority is JWT_ACCESS_EXPIRES_IN in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry; JWT runtime uses environment configuration.',
      catalog: {
        slug: 'security-jwt-access-token-ttl-minutes',
        displayName: 'Access Token TTL Minutes',
        description: 'JWT access token lifetime in minutes',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'features.practitionerApplicationAdminReviewEnabled',
      category: ConfigCategory.SYSTEM,
      domain: 'practitioners',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      status: 'SEEDED_BUT_UNUSED',
      failureMode: 'USE_SAFE_DEFAULT',
      description:
        'Seeded feature catalog entry awaiting an authoritative runtime consumer.',
      catalog: {
        slug: 'features-practitioner-application-admin-review-enabled',
        displayName: 'Practitioner Admin Review Feature',
        description: 'Feature flag controlling admin review operations',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: {
        createInitialValue: true,
        value: true,
        priority: 100,
        effectiveFrom: 'DAYS_AGO_2',
        effectiveTo: 'DAYS_FROM_NOW_365',
      },
    },
    {
      ...base,
      key: 'notifications.channels.default',
      category: ConfigCategory.NOTIFICATION,
      domain: 'notifications',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: ['EMAIL', 'IN_APP'] as const,
      required: true,
      allowedScopes: GLOBAL,
      editable: true,
      allowedValues: Object.values(NotificationChannel),
      status: 'ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description:
        'Seeded default notification channels config.',
      catalog: {
        slug: 'notifications-channels-default',
        displayName: 'Default Notification Channels',
        description: 'Default enabled notification channels',
        configKind: ConfigKind.SETTING,
      },
      seed: {
        createInitialValue: true,
        value: ['EMAIL', 'IN_APP'],
        priority: 100,
      },
      uiMetadata: {
        control: 'multi-select',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'packages.enabled',
      category: ConfigCategory.BOOKING,
      domain: 'packages',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Controls package visibility.',
      catalog: {
        slug: 'packages-enabled',
        displayName: 'Package Plans Enabled',
        description: 'Controls whether standardized package plans are visible',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
      uiMetadata: {
        control: 'toggle',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'packages.purchaseEnabled',
      category: ConfigCategory.BOOKING,
      domain: 'packages',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Controls package purchase availability.',
      catalog: {
        slug: 'packages-purchase-enabled',
        displayName: 'Package Purchases Enabled',
        description:
          'Controls whether package quote and purchase flows are enabled',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
      uiMetadata: {
        control: 'toggle',
        impactTextKey: 'impacts.immediate',
      },
    },
    {
      ...base,
      key: 'payment.provider.paymob.enabled',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL_AND_COUNTRY,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Operational provider flag; credentials remain environment-owned.',
      catalog: {
        slug: 'payment-provider-paymob-enabled',
        displayName: 'Paymob Provider Enabled',
        description: 'Controls whether Paymob can be used for payment routing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.checkoutFlow',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob checkout flow selection.',
      catalog: {
        slug: 'payment-provider-paymob-checkout-flow',
        displayName: 'Paymob Checkout Flow',
        description: 'Selects the active Paymob checkout flow',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.defaultMethod',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob default method selection.',
      catalog: {
        slug: 'payment-provider-paymob-default-method',
        displayName: 'Paymob Default Method',
        description: 'Selects the preferred Paymob checkout method',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.methodRegistry',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'JSON',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      validationStrategy: 'JSON_SCHEMA',
      jsonSchemaId: 'payment.provider.paymob.methodRegistry.v1',
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob method registry metadata.',
      catalog: {
        slug: 'payment-provider-paymob-method-registry',
        displayName: 'Paymob Method Registry',
        description: 'Typed registry for Paymob enabled payment methods',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.maintenanceMode',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: false,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Paymob operational maintenance flag.',
      catalog: {
        slug: 'payment-provider-paymob-maintenance-mode',
        displayName: 'Paymob Maintenance Mode',
        description: 'Temporarily disables Paymob checkout availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.allowedCountries',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob country allowlist.',
      catalog: {
        slug: 'payment-provider-paymob-allowed-countries',
        displayName: 'Paymob Allowed Countries',
        description: 'Allowed country ISO codes for Paymob enabled methods',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.enabled',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL_AND_COUNTRY,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Operational provider flag; credentials remain environment-owned.',
      catalog: {
        slug: 'payment-provider-stripe-enabled',
        displayName: 'Stripe Provider Enabled',
        description: 'Controls whether Stripe can be used for payment routing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.maintenanceMode',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: false,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Stripe operational maintenance flag.',
      catalog: {
        slug: 'payment-provider-stripe-maintenance-mode',
        displayName: 'Stripe Maintenance Mode',
        description: 'Temporarily disables Stripe checkout availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.allowedCountries',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Stripe country allowlist.',
      catalog: {
        slug: 'payment-provider-stripe-allowed-countries',
        displayName: 'Stripe Allowed Countries',
        description: 'Allowed country ISO codes for Stripe availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.defaultProvider',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-default-provider',
        displayName: 'Payment Routing Default Provider',
        description: 'Preferred provider when multiple providers are available',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.priorityOrder',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-priority-order',
        displayName: 'Payment Routing Priority Order',
        description: 'Provider priority order for runtime fallback selection',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.fallbackProvider',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-fallback-provider',
        displayName: 'Payment Routing Fallback Provider',
        description:
          'Fallback provider used when the default provider is unavailable',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.currencyRoutes',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'JSON',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      validationStrategy: 'JSON_SCHEMA',
      jsonSchemaId: 'payment.routing.currencyRoutes.v1',
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Currency routing metadata consumed by payment runtime snapshots.',
      catalog: {
        slug: 'payment-routing-currency-routes',
        displayName: 'Payment Routing Currency Routes',
        description: 'Currency and payment-method-specific provider routes',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'finance.practitionerSharePercent.sameCountry',
      category: ConfigCategory.PAYOUT,
      domain: 'finance',
      owner: 'DATABASE_CONFIG',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 70,
      required: true,
      allowedScopes: GLOBAL_AND_COUNTRY,
      unit: 'percent',
      minimum: 0,
      maximum: 100,
      status: 'ACTIVE',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Practitioner revenue share percentage for same-country patient sessions.',
      catalog: {
        slug: 'finance-practitioner-share-percent-same-country',
        displayName: 'Practitioner Share Percent (Same Country)',
        description: 'Default percentage allocated to practitioner when patient and practitioner share the same country.',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: true, value: 70, priority: 100 },
    },
    {
      ...base,
      key: 'finance.practitionerSharePercent.crossCountry',
      category: ConfigCategory.PAYOUT,
      domain: 'finance',
      owner: 'DATABASE_CONFIG',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 50,
      required: true,
      allowedScopes: GLOBAL_AND_COUNTRY,
      unit: 'percent',
      minimum: 0,
      maximum: 100,
      status: 'ACTIVE',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Practitioner revenue share percentage for cross-country patient sessions.',
      catalog: {
        slug: 'finance-practitioner-share-percent-cross-country',
        displayName: 'Practitioner Share Percent (Cross Country)',
        description: 'Default percentage allocated to practitioner when patient and practitioner are in different countries.',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: true, value: 50, priority: 100 },
    },
    {
      ...base,
      key: 'SESSION_REMINDER_60_MINUTES_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: false,
      status: 'LEGACY',
      deprecatedReplacementKey: 'SESSION_REMINDER_OFFSETS_MINUTES',
      deprecationReason: 'Replaced by the centralized reminder offsets and channel policy.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description: 'Controls durable session reminders sent 60 minutes before start.',
      catalog: {
        slug: 'session-reminder-60-minutes-enabled',
        displayName: 'Session Reminder T-60 Enabled',
        description: 'Enable the session reminder scheduled one hour before start.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'SESSION_REMINDER_15_MINUTES_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: false,
      status: 'LEGACY',
      deprecatedReplacementKey: 'SESSION_REMINDER_OFFSETS_MINUTES',
      deprecationReason: 'Replaced by the centralized reminder offsets and channel policy.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description: 'Controls durable session reminders sent 15 minutes before start.',
      catalog: {
        slug: 'session-reminder-15-minutes-enabled',
        displayName: 'Session Reminder T-15 Enabled',
        description: 'Enable the session reminder scheduled fifteen minutes before start.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'SESSION_START_REMINDER_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: false,
      status: 'LEGACY',
      deprecatedReplacementKey: 'SESSION_REMINDER_OFFSETS_MINUTES',
      deprecationReason: 'Replaced by the centralized reminder offsets and channel policy.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description: 'Controls the at-start session reminder.',
      catalog: {
        slug: 'session-start-reminder-enabled',
        displayName: 'Session Start Reminder Enabled',
        description: 'Enable the reminder sent when the session starts.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'SESSION_LATE_JOIN_REMINDER_ENABLED',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: false,
      status: 'LEGACY',
      deprecatedReplacementKey: 'SESSION_LATE_REMINDER_ENABLED',
      deprecationReason: 'Replaced by the centralized late-reminder policy.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description: 'Controls targeted late-join reminders for participants who have not joined.',
      catalog: {
        slug: 'session-late-join-reminder-enabled',
        displayName: 'Session Late Join Reminder Enabled',
        description: 'Enable the targeted reminder after session start.',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'SESSION_LATE_JOIN_REMINDER_MINUTES',
      category: ConfigCategory.NOTIFICATION,
      domain: 'sessions',
      owner: 'DATABASE_CONFIG',
      valueType: 'INTEGER',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: 5,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 30,
      editable: false,
      status: 'LEGACY',
      deprecatedReplacementKey: 'SESSION_LATE_REMINDER_MINUTES_AFTER_START',
      deprecationReason: 'Replaced by the centralized late-reminder policy.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description: 'Minutes after session start at which the targeted late-join reminder is due.',
      catalog: {
        slug: 'session-late-join-reminder-minutes',
        displayName: 'Session Late Join Reminder Minutes',
        description: 'Delay for the targeted late-join reminder.',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: false },
    },
  ] as const satisfies readonly ConfigDefinition[]),
);
