import { ConfigCategory, ConfigKind, ConfigScopeType } from '@prisma/client';
import { ConfigDefinition } from './config-definition.types';
import { deepFreeze } from './immutable';

const GLOBAL = [ConfigScopeType.GLOBAL] as const;
const GLOBAL_AND_COUNTRY = [
  ConfigScopeType.GLOBAL,
  ConfigScopeType.COUNTRY,
] as const;

const base = {
  required: false,
  editable: false,
  sensitive: false,
  requiresReason: false,
  requiresConfirmation: false,
  requiresStepUp: false,
  snapshotPolicy: 'NONE' as const,
  validationStrategy: 'SCALAR' as const,
  adminVisible: true,
} as const;

export const CONFIG_DEFINITIONS = deepFreeze(
  Object.freeze([
    {
      ...base,
      key: 'platform.defaultLocale',
      category: ConfigCategory.LOCALE,
      domain: 'platform',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      validationStrategy: 'STRING_ENUM',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 'en',
      required: true,
      allowedScopes: GLOBAL_AND_COUNTRY,
      allowedValues: ['ar', 'en'],
      editable: true,
      status: 'SEEDED_BUT_UNUSED',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Catalog fallback locale; current runtime authority is documented separately.',
      catalog: {
        slug: 'platform-default-locale',
        displayName: 'Platform Default Locale',
        description: 'Fallback locale when request locale is missing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: true, value: 'ar', priority: 100 },
    },
    {
      ...base,
      key: 'auth.otp.loginTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'auth',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 10,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 60,
      status: 'LEGACY',
      deprecationReason:
        'Runtime authority is AUTH_LOGIN_OTP_TTL_MINUTES in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry duplicated by the authentication environment policy.',
      catalog: {
        slug: 'auth-otp-login-ttl-minutes',
        displayName: 'Practitioner Login OTP TTL Minutes',
        description: 'OTP validity window in minutes for login flow',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'auth.passwordReset.otpTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'auth',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 15,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 60,
      status: 'LEGACY',
      deprecationReason:
        'Runtime authority is AUTH_RESET_PASSWORD_TTL_MINUTES in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry; reset OTP runtime uses environment configuration.',
      catalog: {
        slug: 'auth-password-reset-otp-ttl-minutes',
        displayName: 'Password Reset OTP TTL Minutes',
        description: 'OTP validity window in minutes for password reset',
        configKind: ConfigKind.LIMIT,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'security.jwt.accessTokenTtlMinutes',
      category: ConfigCategory.SECURITY,
      domain: 'security',
      owner: 'ENV_INFRASTRUCTURE',
      valueType: 'NUMBER',
      defaultPolicy: 'CATALOG_DEFAULT_COMPATIBILITY',
      defaultValue: 30,
      required: true,
      allowedScopes: GLOBAL,
      unit: 'minutes',
      minimum: 1,
      maximum: 1440,
      status: 'LEGACY',
      deprecationReason: 'Runtime authority is JWT_ACCESS_EXPIRES_IN in ENV.',
      failureMode: 'PRESERVE_CATALOG_SEMANTICS',
      description:
        'Legacy catalog entry; JWT runtime uses environment configuration.',
      catalog: {
        slug: 'security-jwt-access-token-ttl-minutes',
        displayName: 'Access Token TTL Minutes',
        description: 'JWT access token lifetime in minutes',
        configKind: ConfigKind.POLICY,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'features.practitionerApplicationAdminReviewEnabled',
      category: ConfigCategory.SYSTEM,
      domain: 'practitioners',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      status: 'SEEDED_BUT_UNUSED',
      failureMode: 'USE_SAFE_DEFAULT',
      description:
        'Seeded feature catalog entry awaiting an authoritative runtime consumer.',
      catalog: {
        slug: 'features-practitioner-application-admin-review-enabled',
        displayName: 'Practitioner Admin Review Feature',
        description: 'Feature flag controlling admin review operations',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: {
        createInitialValue: true,
        value: true,
        priority: 100,
        effectiveFrom: 'DAYS_AGO_2',
        effectiveTo: 'DAYS_FROM_NOW_365',
      },
    },
    {
      ...base,
      key: 'notifications.channels.default',
      category: ConfigCategory.NOTIFICATION,
      domain: 'notifications',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: ['EMAIL', 'IN_APP'],
      required: true,
      allowedScopes: GLOBAL,
      status: 'SEEDED_BUT_UNUSED',
      failureMode: 'USE_SAFE_DEFAULT',
      description:
        'Seeded notification channel preference; no active Config resolver consumer was found.',
      catalog: {
        slug: 'notifications-channels-default',
        displayName: 'Default Notification Channels',
        description: 'Default enabled notification channels',
        configKind: ConfigKind.SETTING,
      },
      seed: {
        createInitialValue: true,
        value: ['EMAIL', 'IN_APP'],
        priority: 100,
      },
    },
    {
      ...base,
      key: 'packages.enabled',
      category: ConfigCategory.BOOKING,
      domain: 'packages',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Controls package visibility.',
      catalog: {
        slug: 'packages-enabled',
        displayName: 'Package Plans Enabled',
        description: 'Controls whether standardized package plans are visible',
        configKind: ConfigKind.FEATURE_DEFAULT,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
    },
    {
      ...base,
      key: 'packages.purchaseEnabled',
      category: ConfigCategory.BOOKING,
      domain: 'packages',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: true,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Controls package purchase availability.',
      catalog: {
        slug: 'packages-purchase-enabled',
        displayName: 'Package Purchases Enabled',
        description:
          'Controls whether package quote and purchase flows are enabled',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: true, value: true, priority: 100 },
    },
    {
      ...base,
      key: 'payment.provider.paymob.enabled',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL_AND_COUNTRY,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Operational provider flag; credentials remain environment-owned.',
      catalog: {
        slug: 'payment-provider-paymob-enabled',
        displayName: 'Paymob Provider Enabled',
        description: 'Controls whether Paymob can be used for payment routing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.checkoutFlow',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob checkout flow selection.',
      catalog: {
        slug: 'payment-provider-paymob-checkout-flow',
        displayName: 'Paymob Checkout Flow',
        description: 'Selects the active Paymob checkout flow',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.defaultMethod',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob default method selection.',
      catalog: {
        slug: 'payment-provider-paymob-default-method',
        displayName: 'Paymob Default Method',
        description: 'Selects the preferred Paymob checkout method',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.methodRegistry',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'JSON',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      validationStrategy: 'JSON_SCHEMA',
      jsonSchemaId: 'payment.provider.paymob.methodRegistry.v1',
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob method registry metadata.',
      catalog: {
        slug: 'payment-provider-paymob-method-registry',
        displayName: 'Paymob Method Registry',
        description: 'Typed registry for Paymob enabled payment methods',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.maintenanceMode',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: false,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Paymob operational maintenance flag.',
      catalog: {
        slug: 'payment-provider-paymob-maintenance-mode',
        displayName: 'Paymob Maintenance Mode',
        description: 'Temporarily disables Paymob checkout availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.paymob.allowedCountries',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Paymob country allowlist.',
      catalog: {
        slug: 'payment-provider-paymob-allowed-countries',
        displayName: 'Paymob Allowed Countries',
        description: 'Allowed country ISO codes for Paymob enabled methods',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.enabled',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL_AND_COUNTRY,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Operational provider flag; credentials remain environment-owned.',
      catalog: {
        slug: 'payment-provider-stripe-enabled',
        displayName: 'Stripe Provider Enabled',
        description: 'Controls whether Stripe can be used for payment routing',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.maintenanceMode',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'BOOLEAN',
      defaultPolicy: 'SAFE_DEFAULT',
      defaultValue: false,
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'USE_SAFE_DEFAULT',
      description: 'Stripe operational maintenance flag.',
      catalog: {
        slug: 'payment-provider-stripe-maintenance-mode',
        displayName: 'Stripe Maintenance Mode',
        description: 'Temporarily disables Stripe checkout availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.provider.stripe.allowedCountries',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description: 'Stripe country allowlist.',
      catalog: {
        slug: 'payment-provider-stripe-allowed-countries',
        displayName: 'Stripe Allowed Countries',
        description: 'Allowed country ISO codes for Stripe availability',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.defaultProvider',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-default-provider',
        displayName: 'Payment Routing Default Provider',
        description: 'Preferred provider when multiple providers are available',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.priorityOrder',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING_ARRAY',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-priority-order',
        displayName: 'Payment Routing Priority Order',
        description: 'Provider priority order for runtime fallback selection',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.fallbackProvider',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'STRING',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      status: 'WRITE_ONLY',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Routing field currently written by admin control but not fully consumed.',
      catalog: {
        slug: 'payment-routing-fallback-provider',
        displayName: 'Payment Routing Fallback Provider',
        description:
          'Fallback provider used when the default provider is unavailable',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
    {
      ...base,
      key: 'payment.routing.currencyRoutes',
      category: ConfigCategory.PAYMENT,
      domain: 'payment',
      owner: 'DATABASE_CONFIG',
      valueType: 'JSON',
      defaultPolicy: 'OPTIONAL_UNAVAILABLE',
      allowedScopes: GLOBAL,
      editable: true,
      validationStrategy: 'JSON_SCHEMA',
      jsonSchemaId: 'payment.routing.currencyRoutes.v1',
      status: 'PARTIALLY_ACTIVE',
      failureMode: 'TREAT_AS_UNAVAILABLE',
      description:
        'Currency routing metadata consumed by payment runtime snapshots.',
      catalog: {
        slug: 'payment-routing-currency-routes',
        displayName: 'Payment Routing Currency Routes',
        description: 'Currency and payment-method-specific provider routes',
        configKind: ConfigKind.SETTING,
      },
      seed: { createInitialValue: false },
    },
  ] as const satisfies readonly ConfigDefinition[]),
);
