import type { PayoutCatalogItem } from "./payout-catalog.types";

export const BANK_CATALOG: PayoutCatalogItem[] = [
  {
    code: "NATIONAL_BANK_OF_EGYPT",
    countryCodes: ["EG"],
    label: { ar: "البنك الأهلي المصري", en: "National Bank of Egypt" },
    aliases: { ar: "الأهلي", en: "NBE" },
    active: true,
    sortOrder: 10,
  },
  {
    code: "BANQUE_MISR",
    countryCodes: ["EG"],
    label: { ar: "بنك مصر", en: "Banque Misr" },
    active: true,
    sortOrder: 20,
  },
  {
    code: "COMMERCIAL_INTERNATIONAL_BANK",
    countryCodes: ["EG"],
    label: { ar: "البنك التجاري الدولي", en: "Commercial International Bank" },
    aliases: { ar: "CIB", en: "CIB" },
    active: true,
    sortOrder: 30,
  },
  {
    code: "QNB_EGYPT",
    countryCodes: ["EG"],
    label: { ar: "كيو إن بي مصر", en: "QNB Egypt" },
    active: true,
    sortOrder: 40,
  },
  {
    code: "HSBC_EGYPT",
    countryCodes: ["EG"],
    label: { ar: "إتش إس بي سي مصر", en: "HSBC Egypt" },
    active: true,
    sortOrder: 50,
  },
  {
    code: "SAUDI_NATIONAL_BANK",
    countryCodes: ["SA"],
    label: { ar: "البنك الأهلي السعودي", en: "Saudi National Bank" },
    aliases: { ar: "الأهلي السعودي", en: "SNB" },
    active: true,
    sortOrder: 10,
  },
  {
    code: "AL_RAJHI_BANK",
    countryCodes: ["SA"],
    label: { ar: "بنك الراجحي", en: "Al Rajhi Bank" },
    active: true,
    sortOrder: 20,
  },
  {
    code: "RIYAD_BANK",
    countryCodes: ["SA"],
    label: { ar: "بنك الرياض", en: "Riyad Bank" },
    active: true,
    sortOrder: 30,
  },
  {
    code: "EMIRATES_NBD",
    countryCodes: ["AE"],
    label: { ar: "الإمارات دبي الوطني", en: "Emirates NBD" },
    active: true,
    sortOrder: 10,
  },
  {
    code: "FIRST_ABU_DHABI_BANK",
    countryCodes: ["AE"],
    label: { ar: "بنك أبوظبي الأول", en: "First Abu Dhabi Bank" },
    aliases: { ar: "FAB", en: "FAB" },
    active: true,
    sortOrder: 20,
  },
  {
    code: "DUBAI_ISLAMIC_BANK",
    countryCodes: ["AE"],
    label: { ar: "بنك دبي الإسلامي", en: "Dubai Islamic Bank" },
    active: true,
    sortOrder: 30,
  },
];
