export enum PermissionKey {
  FINANCE_EVENTS_READ = 'finance.events.read',
  ACCOUNTING_READ = 'finance.accounting.read',
  ACCOUNTING_WRITE = 'finance.accounting.write',
  SETTLEMENTS_READ = 'settlements.read',
  SETTLEMENTS_WRITE = 'settlements.write',
  PRACTITIONER_PAYOUTS_READ = 'practitioner-payouts.read',
  PRACTITIONER_PAYOUTS_WRITE = 'practitioner-payouts.write',
  PRACTITIONER_STATEMENTS_READ = 'practitioner-statements.read',
  NOTIFICATION_OPS_READ = 'notification-ops.read',
  AUDIT_LOG_READ = 'audit-log.read',
  REFUNDS_APPROVE = 'refunds.approve',
  REFUNDS_RETRY = 'refunds.retry',
  SESSIONS_READ_ADMIN = 'sessions.read.admin',
  SESSIONS_READ_SUPPORT_SUMMARY = 'sessions.read.supportSummary',
  CARE_CHAT_REQUEST_DECIDE = 'careChat.request.decide',
  CARE_CHAT_REQUEST_READ_ADMIN = 'careChat.request.read.admin',
  CARE_CHAT_CONVERSATION_READ_ADMIN = 'careChat.conversation.read.admin',
  PATIENTS_READ_ADMIN = 'patients.read.admin',
  PATIENTS_SENSITIVE_READ = 'patients.sensitive.read',
  SUPPORT_TICKET_NOTE_INTERNAL = 'support.ticket.note.internal',
  SUPPORT_TICKET_ASSIGN = 'support.ticket.assign',
}
