export enum PermissionKey {
  FINANCE_EVENTS_READ = 'finance.events.read',
  ACCOUNTING_READ = 'finance.accounting.read',
  ACCOUNTING_WRITE = 'finance.accounting.write',
  SETTLEMENTS_READ = 'settlements.read',
  SETTLEMENTS_WRITE = 'settlements.write',
  PRACTITIONER_PAYOUTS_READ = 'practitioner-payouts.read',
  PRACTITIONER_PAYOUTS_WRITE = 'practitioner-payouts.write',
  PRACTITIONER_STATEMENTS_READ = 'practitioner-statements.read',
  NOTIFICATION_OPS_READ = 'notification-ops.read',
  AUDIT_LOG_READ = 'audit-log.read',
  REFUNDS_APPROVE = 'refunds.approve',
  REFUNDS_RETRY = 'refunds.retry',
  SESSIONS_READ_ADMIN = 'sessions.read.admin',
  SESSIONS_READ_SUPPORT_SUMMARY = 'sessions.read.supportSummary',
  CARE_CHAT_REQUEST_DECIDE = 'careChat.request.decide',
  CARE_CHAT_REQUEST_READ_ADMIN = 'careChat.request.read.admin',
  CARE_CHAT_CONVERSATION_READ_ADMIN = 'careChat.conversation.read.admin',
  CHAT_CONVERSATIONS_READ = 'chat.conversations.read',
  CHAT_CONVERSATIONS_MODERATE = 'chat.conversations.moderate',
  CHAT_ATTACHMENTS_READ = 'chat.attachments.read',
  PATIENTS_READ_ADMIN = 'patients.read.admin',
  PATIENTS_SENSITIVE_READ = 'patients.sensitive.read',
  SUPPORT_TICKET_NOTE_INTERNAL = 'support.ticket.note.internal',
  SUPPORT_TICKET_ASSIGN = 'support.ticket.assign',
  PRACTITIONER_APPLICATIONS_READ = 'practitionerApplications.read',
  PRACTITIONER_APPLICATIONS_APPROVE = 'practitionerApplications.approve',
  PRACTITIONER_APPLICATIONS_REJECT = 'practitionerApplications.reject',
  PRACTITIONER_APPLICATIONS_REQUEST_CHANGES = 'practitionerApplications.requestChanges',

  ADMIN_USERS_READ = 'admin-users.read',
  ADMIN_USERS_CREATE = 'admin-users.create',
  ADMIN_USERS_UPDATE = 'admin-users.update',
  ADMIN_USERS_STATUS_UPDATE = 'admin-users.status.update',
  ADMIN_USERS_ROLES_UPDATE = 'admin-users.roles.update',
  ADMIN_USERS_PERMISSION_OVERRIDES_READ = 'admin-users.permission-overrides.read',
  ADMIN_USERS_PERMISSION_OVERRIDES_UPDATE = 'admin-users.permission-overrides.update',
  ADMIN_USERS_SESSIONS_REVOKE = 'admin-users.sessions.revoke',
  ADMIN_USERS_TOKEN_VERSION_INVALIDATE = 'admin-users.token-version.invalidate',

  // Corporate Voucher Sponsorship
  CORPORATE_ORGANIZATIONS_READ = 'corporate.organizations.read',
  CORPORATE_ORGANIZATIONS_MANAGE = 'corporate.organizations.manage',
  CORPORATE_CONTRACTS_MANAGE = 'corporate.contracts.manage',
  CORPORATE_PLANS_MANAGE = 'corporate.plans.manage',
  CORPORATE_CODES_GENERATE = 'corporate.codes.generate',
  CORPORATE_CODES_EXPORT = 'corporate.codes.export',
  CORPORATE_CODES_REVOKE = 'corporate.codes.revoke',
  CORPORATE_REPORTS_READ = 'corporate.reports.read',
  CORPORATE_LEDGER_READ = 'corporate.ledger.read',

  // Featured Practitioner Placements
  FEATURED_PRACTITIONERS_READ = 'featured-practitioners.read',
  FEATURED_PRACTITIONERS_MANAGE = 'featured-practitioners.manage',
}
