export const mockPatientUser = {
  id: "qa-patient-1",
  displayName: "أحمد — حساب اختبار",
  fullName: "أحمد — حساب اختبار",
  email: "qa-patient@sawiyaa.test",
  phone: "+201012345678",
  status: "ACTIVE",
  roles: ["PATIENT"],
  isEmailVerified: true,
  isPhoneVerified: true,
  avatarUrl: null,
};

export const mockPatientProfile = {
  message: "ok",
  profile: {
    patientProfileId: "prof-qa-1",
    userId: "qa-patient-1",
    displayName: "أحمد — حساب اختبار",
    avatarUrl: null,
    avatarDataUrl: null,
    dateOfBirth: "1992-04-10",
    gender: "MALE",
    locale: "ar",
    countryCode: "EG",
    timezone: "Africa/Cairo",
    isOnboardingCompleted: true,
    onboardingCompletedAt: "2026-01-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-08-20T00:00:00.000Z",
  },
};

export const mockPractitioner1 = {
  id: "prac-1",
  slug: "dr-ahmed-fayed",
  displayName: "د. أحمد فايد",
  title: "استشاري الطب النفسي وعلاج الإدمان",
  professionalTitle: "استشاري الطب النفسي وعلاج الإدمان",
  headline: "خبرة أكثر من 15 عاماً في العلاج النفسي والاستشارات الأسرية",
  bio: "طبيب استشاري متخصص في علاج القلق والاكتئاب والاضطرابات الوجدانية، حاصل على الدكتوراه في الطب النفسي.",
  avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
  isVerified: true,
  ratingSummary: {
    averageRating: 4.95,
    totalReviews: 128,
  },
  sessionCount: 1420,
  yearsOfExperience: 15,
  country: "EG",
  city: "القاهرة",
  timezone: "Africa/Cairo",
  isAvailableToday: true,
  isOnline: false,
  currencyCode: "EGP",
  sessionPrice30: "450.00",
  sessionPrice60: "800.00",
  displaySessionPrice30: "450.00",
  displaySessionPrice60: "800.00",
  pricing: {
    currency: "EGP",
    duration30: 450,
    duration60: 800,
  },
  specialties: [
    { specialtyId: "s1", slug: "depression", title: "الاكتئاب", isPrimary: true },
    { specialtyId: "s2", slug: "anxiety", title: "اضطرابات القلق", isPrimary: false },
    { specialtyId: "s3", slug: "cbt", title: "العلاج المعرفي السلوكي", isPrimary: false },
    { specialtyId: "s4", slug: "couples-counseling", title: "الاستشارات الزوجية", isPrimary: false },
  ],
  supportedDurations: [30, 60],
  nextAvailableSlot: "2026-09-08T10:00:00.000Z",
};

export const mockPractitioner2 = {
  id: "prac-2",
  slug: "dr-sarah-khalil",
  displayName: "د. سارة خليل",
  title: "أخصائية العلاج النفسي للأطفال والمراهقين",
  professionalTitle: "أخصائية العلاج النفسي للأطفال والمراهقين",
  headline: "ماجستير الصحة النفسية والعلاج السلوكي المعرفي",
  bio: "متخصصة في مشاكل المراهقة، اضطراب فرط الحركة، ودعم الوالدين والتربية الإيجابية.",
  avatarUrl: "https://images.unsplash.com/photo-1594824813581-789f7435f3da?w=300",
  isVerified: true,
  ratingSummary: {
    averageRating: 4.88,
    totalReviews: 94,
  },
  sessionCount: 850,
  yearsOfExperience: 10,
  country: "EG",
  city: "الإسكندرية",
  timezone: "Africa/Cairo",
  isAvailableToday: true,
  isOnline: false,
  currencyCode: "EGP",
  sessionPrice30: "400.00",
  sessionPrice60: "700.00",
  displaySessionPrice30: "400.00",
  displaySessionPrice60: "700.00",
  pricing: {
    currency: "EGP",
    duration30: 400,
    duration60: 700,
  },
  specialties: [
    { specialtyId: "s5", slug: "adolescent-health", title: "صحة المراهقين", isPrimary: true },
    { specialtyId: "s6", slug: "adhd", title: "فرط الحركة وتشتت الانتباه", isPrimary: false },
    { specialtyId: "s7", slug: "school-anxiety", title: "القلق المدرسي", isPrimary: false },
  ],
  supportedDurations: [30, 60],
  nextAvailableSlot: "2026-09-08T14:30:00.000Z",
};

export const mockPractitionersList = {
  items: [mockPractitioner1, mockPractitioner2],
  pagination: {
    page: 1,
    limit: 10,
    total: 2,
    totalPages: 1,
  },
};

export const mockNextSession = {
  sessionId: "sess-ready-1",
  role: "PATIENT",
  counterpart: {
    displayName: "د. أحمد فايد",
    avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
  },
  startsAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
  scheduledEndAt: new Date(Date.now() + 40 * 60 * 1000).toISOString(),
  durationMinutes: 30,
  displayTimezone: "Africa/Cairo",
  status: "READY_TO_JOIN",
  detailsRoute: "/(patient)/sessions/sess-ready-1",
  joinRoute: "/(patient)/sessions/sess-ready-1",
  operational: {
    state: "READY_TO_JOIN",
    reasonCode: null,
    join: { allowed: true, reasonCode: null, canPrepareRuntime: true, opensAt: null, closesAt: null },
    actions: { canJoin: true, canPrepareRuntime: true, canCancel: false, canPay: false, canReview: false, canMarkPatientNoShow: false, noShowReasonCode: null },
    room: { state: "OPEN", closedAt: null },
    resolution: { required: false, finalDecision: null },
  },
};

export const mockSessionsList = [
  {
    id: "sess-ready-1",
    sessionCode: "SW-84920",
    scheduledStartAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    scheduledEndAt: new Date(Date.now() + 40 * 60 * 1000).toISOString(),
    durationMinutes: 30,
    status: "READY_TO_JOIN",
    sessionMode: "VIDEO",
    meetingUrl: "https://meet.sawiyaa.com/session/sess-ready-1",
    practitioner: {
      id: "prac-1",
      slug: "dr-ahmed-fayed",
      displayName: "د. أحمد فايد",
      professionalTitle: "استشاري الطب النفسي",
      avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
    },
    patient: {
      id: "qa-patient-1",
      displayName: "أحمد — حساب اختبار",
    },
    actions: {
      canJoin: true,
      canPay: false,
      canReview: false,
      canCancel: false,
    },
    chatAvailability: {
      isAvailable: true,
      canInitiate: true,
    },
    operational: {
      state: "READY_TO_JOIN",
      timelineBucket: "ACTIVE",
      actions: {
        canJoin: true,
        canPay: false,
        canReview: false,
        canCancel: false,
      },
    },
  },
  {
    id: "sess-pay-2",
    sessionCode: "SW-84921",
    scheduledStartAt: new Date(Date.now() + 2 * 3600 * 1000 * 24).toISOString(),
    scheduledEndAt: new Date(Date.now() + 3 * 3600 * 1000 * 24).toISOString(),
    durationMinutes: 60,
    status: "PENDING_PAYMENT",
    sessionMode: "VIDEO",
    practitioner: {
      id: "prac-2",
      slug: "dr-sarah-khalil",
      displayName: "د. سارة خليل",
      professionalTitle: "أخصائية العلاج السلوكي",
      avatarUrl: "https://images.unsplash.com/photo-1594824813581-789f7435f3da?w=300",
    },
    patient: {
      id: "qa-patient-1",
      displayName: "أحمد — حساب اختبار",
    },
    actions: {
      canJoin: false,
      canPay: true,
      canReview: false,
      canCancel: true,
    },
    chatAvailability: {
      isAvailable: false,
      canInitiate: false,
    },
    operational: {
      state: "PENDING_PAYMENT",
      timelineBucket: "UPCOMING",
      actions: {
        canJoin: false,
        canPay: true,
        canReview: false,
        canCancel: true,
      },
    },
  },
  {
    id: "sess-hist-3",
    sessionCode: "SW-84915",
    scheduledStartAt: "2026-08-20T11:00:00.000Z",
    scheduledEndAt: "2026-08-20T11:30:00.000Z",
    durationMinutes: 30,
    status: "COMPLETED",
    sessionMode: "VIDEO",
    practitioner: {
      id: "prac-1",
      slug: "dr-ahmed-fayed",
      displayName: "د. أحمد فايد",
      professionalTitle: "استشاري الطب النفسي",
      avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
    },
    patient: {
      id: "qa-patient-1",
      displayName: "أحمد — حساب اختبار",
    },
    actions: {
      canJoin: false,
      canPay: false,
      canReview: true,
      canCancel: false,
    },
    chatAvailability: {
      isAvailable: true,
      canInitiate: true,
    },
    operational: {
      state: "COMPLETED",
      timelineBucket: "COMPLETED",
      actions: {
        canJoin: false,
        canPay: false,
        canReview: true,
        canCancel: false,
      },
    },
  },
];

export const mockWallet = {
  id: "w-1",
  currencyCode: "EGP",
  availableBalance: "100.00",
  reservedBalance: "0.00",
  lifetimeCredited: "100.00",
  lifetimeDebited: "0.00",
  lastEntryAt: "2026-08-28T14:20:00.000Z",
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-08-28T14:20:00.000Z",
  entries: [
    {
      id: "w-entry-1",
      amount: "100.00",
      currencyCode: "EGP",
      direction: "CREDIT",
      entryType: "REFUND_CREDIT",
      titleKey: "refund",
      statusKey: "completed",
      source: "wallet",
      occurredAt: "2026-08-28T14:20:00.000Z",
      createdAt: "2026-08-28T14:20:00.000Z",
      effectiveAt: "2026-08-28T14:20:00.000Z",
    },
    {
      id: "w-entry-2",
      amount: "450.00",
      currencyCode: "EGP",
      direction: "DEBIT",
      entryType: "SESSION_PAYMENT_CAPTURE",
      titleKey: "sessionPayment",
      statusKey: "completed",
      source: "payment",
      sessionId: "sess-hist-3",
      occurredAt: "2026-08-20T10:45:00.000Z",
      createdAt: "2026-08-20T10:45:00.000Z",
      effectiveAt: "2026-08-20T10:45:00.000Z",
    },
  ],
};

export const mockNotifications = [
  {
    id: "notif-1",
    title: "جلستك جاهزة للدخول",
    body: "يمكنك الآن الانضمام لجلستك مع د. أحمد فايد عبر رابط الفيديو المباشر.",
    typeSlug: "session.join_available",
    category: "SESSION",
    readAt: null,
    createdAt: new Date().toISOString(),
    action: { type: "INTERNAL_LINK", href: "/patient/sessions/sess-ready-1", label: "Open session" },
    payload: { sessionId: "sess-ready-1" },
    context: { practitionerName: "د. أحمد فايد", sessionCode: "SW-84920" },
    primaryAction: { kind: "session", id: "sess-ready-1", href: "/patient/sessions/sess-ready-1" },
  },
  {
    id: "notif-2",
    title: "تم تأكيد موعد جلستك",
    body: "تم تأكيد جلستك القادمة بنجاح مع د. سارة خليل.",
    typeSlug: "session.confirmed",
    category: "SESSION",
    readAt: "2026-08-28T09:20:00.000Z",
    createdAt: "2026-08-28T09:15:00.000Z",
    action: { type: "INTERNAL_LINK", href: "/patient/sessions/sess-pay-2", label: "Open session" },
    payload: { sessionId: "sess-pay-2" },
    context: { practitionerName: "د. سارة خليل", sessionCode: "SW-84921" },
    primaryAction: { kind: "session", id: "sess-pay-2", href: "/patient/sessions/sess-pay-2" },
  },
];

export const mockConversations = [
  {
    id: "conv-1",
    counterpart: {
      id: "prac-1",
      displayName: "د. أحمد فايد",
      avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300",
      role: "PRACTITIONER",
    },
    contextTitle: "جلسة المتابعة النفسية",
    lastMessage: {
      body: "أهلاً بك، يمكنك مشاركة أي استفسارات أو ملاحظات قبل موعد جلستنا.",
      sentAt: "2026-08-29T08:00:00.000Z",
      senderRole: "PRACTITIONER",
      isUnread: true,
    },
    unreadCount: 1,
  },
];
