ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_CARE_CHAT_REVOKE';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_CARE_CHAT_MESSAGE_HIDE';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_REVIEW_HIDE';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_REVIEW_REJECT';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_REVIEW_RESTORE';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_ARTICLE_ARCHIVE';
ALTER TYPE "ModerationCaseActionType" ADD VALUE IF NOT EXISTS 'ENFORCE_SUPPORT_ESCALATE';
