import React, { useEffect, useMemo, useState } from "react";
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from "react-native";
import { useLocalSearchParams, useNavigation, useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useTranslation } from "react-i18next";
import { Button, Card, Header, LoadingState, Screen, Text } from "../../../src/components/ui";
import { useTheme } from "../../../src/providers/ThemeProvider";
import { useAvailabilityWeekDetails, useCreateAvailabilityWeek, useUpdateAvailabilityWeek } from "../../../src/features/practitioner/availability/hooks";
import { emptySelectedTimes, formatMinuteRange, selectedTimesEqual, selectedTimesToSlots, slotsToSelectedTimes, timeOptions, type DayOfWeek, type DurationMinutes, type SelectedTimes } from "../../../src/features/practitioner/availability/utils";

export default function AvailabilityWeekEditorScreen() {
  const params = useLocalSearchParams<{ weekId?: string; weekStartDate?: string; timezone?: string }>(); const router = useRouter(); const navigation = useNavigation(); const { t, i18n } = useTranslation(); const { theme } = useTheme();
  const details = useAvailabilityWeekDetails(params.weekId); const create = useCreateAvailabilityWeek(); const update = useUpdateAvailabilityWeek(); const rtl = i18n.dir() === "rtl";
  const [duration, setDuration] = useState<DurationMinutes>(30); const [day, setDay] = useState<DayOfWeek>(1); const [selected, setSelected] = useState<SelectedTimes>(emptySelectedTimes); const [initial, setInitial] = useState<SelectedTimes>(emptySelectedTimes);
  const week = details.data?.week; const timezone = week?.timezone ?? params.timezone ?? "";
  const protectedKeys = useMemo(() => new Set((week?.slots ?? []).filter((slot) => slot.canEdit === false || slot.canRemove === false || slot.isBookedOrReserved).map((slot) => `${slot.dayOfWeek}:${slot.durationMinutes}:${slot.startMinuteOfDay}`)), [week?.slots]);
  useEffect(() => { if (week) { const value = slotsToSelectedTimes(week.slots); setSelected(value); setInitial(value); } }, [week]);
  const dirty = useMemo(() => !selectedTimesEqual(selected, initial), [selected, initial]);
  useEffect(() => navigation.addListener("beforeRemove", (event) => {
    if (!dirty) return;
    event.preventDefault();
    Alert.alert(t("practitioner.availability.discardTitle"), t("practitioner.availability.discardBody"), [
      { text: t("common.cancel"), style: "cancel" },
      { text: t("common.discard"), style: "destructive", onPress: () => navigation.dispatch(event.data.action) },
    ]);
  }), [dirty, navigation, t]);
  const toggle = (minute: number) => { if (week && !week.isEditable) return; if (protectedKeys.has(`${day}:${duration}:${minute}`)) return; setSelected((current) => ({ ...current, [duration]: { ...current[duration], [day]: current[duration][day].includes(minute) ? current[duration][day].filter((x) => x !== minute) : [...current[duration][day], minute].sort((a, b) => a - b) } })); };
  const save = () => { if (!timezone) { Alert.alert(t("common.error"), t("practitioner.availability.timezoneRequired")); return; } const slots = selectedTimesToSlots(selected); if (params.weekId) update.mutate({ weekId: params.weekId, payload: { timezone, slots } }, { onSuccess: () => { setInitial(selected); router.back(); }, onError: () => Alert.alert(t("common.error"), t("practitioner.availability.actionError")) }); else create.mutate({ weekStartDate: params.weekStartDate!, timezone, slots }, { onSuccess: (data) => { setInitial(selected); router.replace(`/(practitioner)/availability/${data.week.id}` as never); }, onError: () => Alert.alert(t("common.error"), t("practitioner.availability.actionError")) }); };
  if (params.weekId && (details.isLoading || !week)) return <Screen><Header showBack title={t("practitioner.availability.editorTitle")} /><LoadingState message={t("practitioner.availability.loading")} /></Screen>;
  const days = [0, 1, 2, 3, 4, 5, 6] as DayOfWeek[]; const dayKeys = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];
  return <Screen><Header showBack title={t("practitioner.availability.editorTitle")} /><ScrollView contentContainerStyle={styles.content}>
    <Text variant="caption" color={theme.colors.textSecondary} style={styles.center}>{t("practitioner.availability.editorBody")}</Text>
    <View style={[styles.segment, { flexDirection: rtl ? "row-reverse" : "row" }]}>{([30, 60] as DurationMinutes[]).map((value) => <TouchableOpacity key={value} onPress={() => setDuration(value)} accessibilityRole="tab" accessibilityState={{ selected: duration === value }} accessibilityLabel={t("practitioner.availability.duration", { count: value })} style={[styles.segmentItem, { backgroundColor: duration === value ? theme.colors.primary : theme.colors.surfaceRaised }]}><Text color={duration === value ? theme.colors.onPrimary : theme.colors.textPrimary}>{t("practitioner.availability.duration", { count: value })}</Text></TouchableOpacity>)}</View>
    <View style={[styles.days, { flexDirection: rtl ? "row-reverse" : "row" }]}>{days.map((value) => <TouchableOpacity key={value} onPress={() => setDay(value)} accessibilityRole="tab" accessibilityState={{ selected: day === value }} accessibilityLabel={t(`practitioner.availability.weeks.days.${dayKeys[value]}`)} style={[styles.day, { backgroundColor: day === value ? theme.colors.primarySoft : theme.colors.surfaceRaised }]}><Text variant="caption" weight="700">{t(`practitioner.availability.weeks.days.${dayKeys[value]}`).slice(0, 3)}</Text></TouchableOpacity>)}</View>
    <Card variant="outlined" padding="sm" style={styles.grid}>{timeOptions(duration).map((minute) => { const active = selected[duration][day].includes(minute); const protectedTime = protectedKeys.has(`${day}:${duration}:${minute}`); return <TouchableOpacity key={minute} onPress={() => toggle(minute)} disabled={protectedTime} accessibilityRole="button" accessibilityState={{ selected: active, disabled: protectedTime }} accessibilityLabel={`${formatMinuteRange(minute, duration, rtl)}${protectedTime ? `, ${t("practitioner.availability.protectedSlot")}` : ""}`} style={[styles.time, { backgroundColor: active ? theme.colors.primarySoft : theme.colors.surfaceRaised, borderColor: active ? theme.colors.primary : theme.colors.border, opacity: protectedTime ? 0.7 : 1 }]}><Text variant="caption" color={active ? theme.colors.primary : theme.colors.textPrimary}>{formatMinuteRange(minute, duration, rtl)}</Text>{protectedTime ? <Ionicons name="lock-closed-outline" size={12} color={theme.colors.textMuted} /> : null}</TouchableOpacity>; })}</Card>
    {week?.status === "PUBLISHED" ? <Text variant="caption" color={theme.colors.textSecondary} style={styles.note}>{t("practitioner.availability.publishedEditNote")}</Text> : null}{dirty ? <Text variant="caption" color={theme.colors.warning} style={styles.note}>{t("practitioner.availability.unsavedChanges")}</Text> : null}
    <Button title={t("practitioner.availability.saveWeek")} onPress={save} loading={create.isPending || update.isPending} disabled={!dirty} /><Button title={t("common.cancel")} variant="secondary" onPress={() => dirty ? Alert.alert(t("practitioner.availability.discardTitle"), t("practitioner.availability.discardBody"), [{ text: t("common.cancel"), style: "cancel" }, { text: t("common.discard"), onPress: () => router.back() }]) : router.back()} style={styles.cancel} />
  </ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 32 }, center: { textAlign: "center", marginBottom: 16 }, segment: { borderWidth: 1, borderColor: "#D7DDD9", borderRadius: 12, padding: 4, marginBottom: 12 }, segmentItem: { flex: 1, alignItems: "center", padding: 11, borderRadius: 9 }, days: { gap: 5, marginBottom: 12 }, day: { flex: 1, minHeight: 42, alignItems: "center", justifyContent: "center", borderRadius: 9, paddingHorizontal: 2 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, time: { width: "31.5%", minHeight: 42, borderWidth: 1, borderRadius: 9, alignItems: "center", justifyContent: "center" }, note: { textAlign: "center", marginVertical: 12 }, cancel: { marginTop: 10 } });
