import React from "react";
import { Alert, ScrollView, StyleSheet, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useTranslation } from "react-i18next";
import { Button, Card, Header, Screen, Text } from "../../../src/components/ui";
import { useConfirmAvailabilityWeekRepeat, useMyAvailabilityWeeks } from "../../../src/features/practitioner/availability/hooks";
import type { AvailabilityRepeatConfirmation, AvailabilityRepeatPreview } from "../../../src/features/practitioner/availability/types";
import { useTheme } from "../../../src/providers/ThemeProvider";

export default function RepeatReviewScreen() {
  const params = useLocalSearchParams<{ sourceWeekId: string; targetWeekStartDates: string; preview: string; idempotencyKey: string }>(); const router = useRouter(); const { t } = useTranslation(); const { theme } = useTheme(); const confirm = useConfirmAvailabilityWeekRepeat(); const weeksQuery = useMyAvailabilityWeeks(); const [confirmation, setConfirmation] = React.useState<AvailabilityRepeatConfirmation | null>(null);
  let preview: AvailabilityRepeatPreview | null = null; try { preview = JSON.parse(params.preview) as AvailabilityRepeatPreview; } catch { /* route data is validated below */ }
  if (!preview) return <Screen><Header showBack title={t("practitioner.availability.repeatReviewTitle")} /><Text style={styles.center}>{t("practitioner.availability.previewUnavailable")}</Text></Screen>;
  const confirmRepeat = () => Alert.alert(t("practitioner.availability.confirmRepeatTitle"), t("practitioner.availability.confirmRepeatBody"), [{ text: t("common.cancel"), style: "cancel" }, { text: t("common.confirm"), onPress: () => confirm.mutate({ sourceWeekId: params.sourceWeekId, operationId: preview!.operationId, idempotencyKey: params.idempotencyKey }, { onSuccess: (result) => { setConfirmation(result); void weeksQuery.refetch(); }, onError: () => Alert.alert(t("common.error"), t("practitioner.availability.repeatExpired")) }) }]);
  const openCreatedWeek = async () => { const result = await weeksQuery.refetch(); const created = result.data?.weeks.find((week) => confirmation?.targets.some((target) => target.weekStartDate === week.weekStartDate && target.classification === "ELIGIBLE") && week.weekId); if (created?.weekId) router.replace(`/(practitioner)/availability/${created.weekId}` as never); else router.replace("/(practitioner)/availability" as never); };
  return <Screen><Header showBack title={t("practitioner.availability.repeatReviewTitle")} /><ScrollView contentContainerStyle={styles.content}><Text variant="caption" color={theme.colors.textSecondary} style={styles.center}>{t("practitioner.availability.repeatReviewBody")}</Text>{preview.targets.map((target) => { const result = confirmation?.targets.find((item) => item.weekStartDate === target.weekStartDate) ?? target; return <Card key={target.weekStartDate} variant="outlined" padding="md" style={styles.card}><View style={styles.row}><Text weight="700">{target.weekStartDate}</Text><Text color={result.classification === "ELIGIBLE" ? theme.colors.success : theme.colors.warning}>{t(`practitioner.availability.repeat.${result.classification.toLowerCase()}`)}</Text></View><Text variant="caption" color={theme.colors.textSecondary}>{result.classification === "ELIGIBLE" ? t("practitioner.availability.repeatSlots", { count: result.copiedSlotCount }) : t(`practitioner.availability.repeatReasons.${result.reasonCode}`, { defaultValue: result.reasonCode })}</Text></Card>; })}{confirmation ? <><Text variant="caption" color={theme.colors.success} style={styles.center}>{t("practitioner.availability.repeatSuccess")}</Text><Button title={t("practitioner.availability.openCreatedWeek", { defaultValue: "Open created week" })} onPress={() => void openCreatedWeek()} /></> : <Button title={t("practitioner.availability.confirmRepeat")} onPress={confirmRepeat} loading={confirm.isPending} disabled={!preview.confirmationAllowed} />}</ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 32 }, center: { textAlign: "center", marginBottom: 16 }, card: { marginBottom: 10, borderRadius: 14 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 } });
