import React, { useState } from "react";
import { Alert, ScrollView, StyleSheet, TouchableOpacity, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useTranslation } from "react-i18next";
import { Button, Card, Header, Screen, Text } from "../../../src/components/ui";
import { useMyAvailabilityWeeks, usePreviewAvailabilityWeekRepeat } from "../../../src/features/practitioner/availability/hooks";
import { formatWeekRange } from "../../../src/features/practitioner/availability/utils";
import { useTheme } from "../../../src/providers/ThemeProvider";

export default function RepeatTargetsScreen() {
  const { sourceWeekId } = useLocalSearchParams<{ sourceWeekId: string }>(); const router = useRouter(); const { t, i18n } = useTranslation(); const { theme } = useTheme(); const query = useMyAvailabilityWeeks(); const preview = usePreviewAvailabilityWeekRepeat(); const [selected, setSelected] = useState<string[]>([]); const [idempotencyKey] = useState(() => `mobile-repeat-${sourceWeekId}-${Date.now()}`);
  const weeks = query.data?.weeks.filter((week) => week.weekId !== sourceWeekId && week.relativeWeekIndex > 0) ?? [];
  const toggle = (date: string) => { if (!weeks.find((week) => week.weekStartDate === date)?.canCreate) return; setSelected((current) => current.includes(date) ? current.filter((value) => value !== date) : [...current, date]); };
  const next = () => { if (!selected.length) { Alert.alert(t("common.error"), t("practitioner.availability.selectRepeatTarget")); return; } preview.mutate({ sourceWeekId, targetWeekStartDates: selected, idempotencyKey }, { onSuccess: (data) => router.push({ pathname: "/(practitioner)/availability/repeat-review" as never, params: { sourceWeekId, targetWeekStartDates: JSON.stringify(selected), preview: JSON.stringify(data), idempotencyKey } } as never), onError: () => Alert.alert(t("common.error"), t("practitioner.availability.actionError")) }); };
  return <Screen><Header showBack title={t("practitioner.availability.repeatTitle")} /><ScrollView contentContainerStyle={styles.content}><Text variant="caption" color={theme.colors.textSecondary} style={styles.center}>{t("practitioner.availability.repeatBody")}</Text>{weeks.map((week) => { const active = selected.includes(week.weekStartDate); const disabled = !week.canCreate; const reason = week.status === "PUBLISHED" ? "TARGET_PUBLISHED" : week.containsBookings ? "TARGET_HAS_BOOKINGS" : "TARGET_ALREADY_EXISTS"; return <TouchableOpacity key={week.weekStartDate} onPress={() => toggle(week.weekStartDate)} disabled={disabled} accessibilityRole="checkbox" accessibilityState={{ checked: active, disabled }} accessibilityLabel={formatWeekRange(week.weekStartDate, week.weekEndDate, i18n.language)}><Card variant="outlined" padding="md" style={[styles.card, active && { borderColor: theme.colors.primary, backgroundColor: theme.colors.primarySoft }, disabled && { opacity: 0.6 }]}><View style={styles.row}><Text weight="700">{formatWeekRange(week.weekStartDate, week.weekEndDate, i18n.language)}</Text><Text color={active ? theme.colors.primary : theme.colors.textMuted}>{active ? "✓" : "○"}</Text></View><Text variant="caption" color={theme.colors.textSecondary}>{disabled ? t(`practitioner.availability.repeatReasons.${reason}`, { defaultValue: reason }) : t(`practitioner.availability.status.${week.status}`)}</Text></Card></TouchableOpacity>; })}<Button title={t("practitioner.availability.reviewRepeat")} onPress={next} loading={preview.isPending} disabled={!selected.length} /></ScrollView></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 32 }, center: { textAlign: "center", marginBottom: 16 }, card: { marginBottom: 10, borderRadius: 14 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 } });
